name: run-gpu-tests
on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Print GitHub workspace
        run: |
          echo "${{ github.workspace }}"
          pwd

